### ISSUE TITLE
Mutable globals for improved compiled push performance 

### ISSUE THREAD

**Issue by remko** [remko/waforth#1]
Right now, compiled words use `call_indirect` to push and pop data on the stack. Need to investigate if this can be improved upon.

See if using the experimental [mutable globals](https://github.com/WebAssembly/mutable-global) help.

**Comment by binji** [comment]
An implementation of the mutable globals proposal is available in a few browsers now, behind a flag. You can try it out in Chrome Dev or Chrome Canary by passing a v8 flag to Chrome (see [here](https://www.chromium.org/developers/how-tos/run-chromium-with-flags)). I think it would be `--js-flags="--experimental-wasm-mut-global"` but I haven't tried it out.

**Comment by remko** [comment]
Awesome, thanks for the tip! I’ll try it out.

**Comment by remko** [comment]
@binji Unfortunately, switching to Chrome Canary (69.0.3443.0) or Dev (68.0.3438.3) makes everything 6x slower, without touching any code or even turning on the v8 flag. I guess I'll have to wait a bit, but I hope things won't regress this bad.

**Comment by binji** [comment]
Thanks for the info, do you have a test script for this? I'd like to bisect to see where this perf regression occurs.

**Comment by remko** [comment]
@binji Here it is: [sieve.zip](https://github.com/remko/waforth/files/2048018/sieve.zip)
It runs the benchmark 3 times. I expect a runtime of about 5s per run with the most recent stable Chrome, and get about 20s for canary. If you want to shorten the test, look for `5e7` in the .js file and make that number a bit smaller.

**Comment by binji** [comment]
I spoke w/ a colleague on v8 and he said that it was likely that this regression occurs because of spectre mitigations. I hacked your example to run on the console version of v8, and this seems to be correct:

```
$ d8 sieve.js 
Loading...
<div>Running...</div>
<div><pre style='display: inline-block; margin: 0; margin-right: 1rem'>778849999991 ok
</pre><span>21.467419999999997</span></div>
...
```

```
$ d8 sieve.js --no-untrusted-code-mitigations
Loading...
<div>Running...</div>
<div><pre style='display: inline-block; margin: 0; margin-right: 1rem'>778849999991 ok
</pre><span>8.295259</span></div>
...
```

There are plans to improve this in the near future, but currently this is an expected regression, unfortunately.

**Comment by remko** [comment]
Thanks for looking into this and for the explanation.

**Comment by remko** [comment]
@binji In case you’re interested: all the slowdown is due to `call_indirect`. The benchmark heavily uses these. If I replace all these by regular `call` instructions, I get the same times in Canary and Stable.

**Comment by remko** [comment]
This is implemented on the [`mutable-globals` branch](https://github.com/remko/waforth/tree/mutable-globals).

On Chrome, this gives a decent performance improvement:

Before: 
<img width="499" alt="chrome-mutable-globals-before" src="https://user-images.githubusercontent.com/12300/40804741-856adf6a-651c-11e8-8ddd-5df51d58fc8c.png">

After:
<img width="495" alt="chrome-mutable-globals-after" src="https://user-images.githubusercontent.com/12300/40805345-3ff1ccb2-651e-11e8-8bf6-d2fd64899b4d.png">

Unfortunately, the (temporary) slowdown due to the spectre mitigation mentioned above spoils the fun.

On Firefox (62.0a1 (2018-05-30)), the improvement is less noticeable, because simply exporting a mutable global seems to cause some overhead on itself (probably because of boxing?):

Before:
<img width="492" alt="firefox-mutable-globals-before" src="https://user-images.githubusercontent.com/12300/40805282-0a8e9cb2-651e-11e8-92d8-55307f1a7790.png">

After:
<img width="501" alt="firefox-mutable-globals-after" src="https://user-images.githubusercontent.com/12300/40805351-4455d6c2-651e-11e8-871c-44ed7024df11.png">

Exporting the mutable global (but not using it or changing the generated code):
<img width="487" alt="firefox-mutable-globals-between" src="https://user-images.githubusercontent.com/12300/40805297-19c15c38-651e-11e8-9f20-2daafd2d9777.png">
