### ISSUE TITLE
Replace memcopy and memset with bulk operation

### ISSUE THREAD

**Issue by remko** [remko/waforth#10]
See https://github.com/WebAssembly/design/issues/1114#thread-subscription-status

**Comment by mko-io** [comment]
Hi remko, Bulk memory operation has [enable by default](https://www.chromestatus.com/feature/4590306448113664) on chrome 75. Do you want give it a try?

**Comment by remko** [comment]
Thanks for the heads up!

I implemented a conditional to replace the current implementations with the built-in ones. It works, and obviously saves a few lines of code and bytes.

Unfortunately, since bulk memory operations are only used in the compiler (which isn't part of the speed test I run) and words not used in the benchmark, I can't really measure any effect. The compiler only uses it for copying tiny regions, so it won't really matter for speed anyway.
