### ISSUE TITLE
Runtime errors freeze shell

### ISSUE THREAD

**Issue by hellerve** [remko/waforth#12]
**What did I do?**
I force a runtime error (e.g. by typing `/` into a fresh shell, leading to a divide by zero).

**What did I expect to happen?**
I expect an error message to be logged on screen.

**What happens instead?**
The shell freezes and becomes unresponsive. The error is logged in the console.

Cheers

**Comment by remko** [comment]
Yeah, errors are still a huge pain in the ass. It depends on the type of error you get; sometimes you'll get `error` printed on console, and it leaves everything in a bad state; sometimes it's an assertion in WebAssembly, in which case everything probably crashes. I need to see what I can do about both cases. 

This is probably related to a good implementation of ABORT, ABORT", QUIT etc. ( #4 ). 

Printing decent messages is probably doable. However, given that it's impossible to do non-local jumps in WebAssembly, it may be that actually recovering from errors (resetting stacks etc.) may depend on [WebAssembly Exception Handling Proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md) ever being standardized. Unless there's an ugly workaround (and hopefully not as ugly as error return codes that have to be checked on every instruction).

**Comment by remko** [comment]
- Errors no longer freeze the shell
- Error messages are (usually) printed when something goes wrong
- Added check for division by 0 in `/`
