### ISSUE TITLE
Support calling JavaScript from Forth

### ISSUE THREAD

**Issue by yunfan** [remko/waforth#13]
i think if waforth could interacting with js, that would be much more fun

**Comment by remko** [comment]
What sort of interaction were you thinking about? Simply calling Forth from JS and vice versa, or do you mean a visualization?

**Comment by remko** [comment]
Do you mean an example in the documentation on how to call Forth from JS?

**Comment by yunfan** [comment]
sorry i mean the reverse forward, calling js from forth, like use js to invoke canvas api to draw a circle on the host enviroment

**Comment by remko** [comment]
You're right, that would be nice!

**Comment by Zireael07** [comment]
Any news?

**Comment by remko** [comment]
@Zireael07 I have some concrete plans for it now, and it's high on my list.

**Comment by remko** [comment]
I did an initial attempt at an API to call JS from Forth. You can see a working example [here](https://github.com/remko/waforth/blob/master/src/web/examples/prompt/prompt.ts). More interesting examples will probably come later.

**Comment by Quleaf** [comment]
i had heard it from the turtle example news :dagger: 
will try the new feature, thank you very much for your work

**Comment by yunfan** [comment]
Thanks for finally completed this. i had checked this from the turtle news at reddit
