### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by andydude** [remko/waforth#52]
I ran the dev server with `yarn dev` and this is what I see on the terminal:

```
listening on port 8080
[watch] build finished, watching for changes...
```

and this is what I see in the browser:

```
WAForth (dev)
Loading core ... error
```

it doesn't seem to be responsive, and it doesn't seem to work. Am I missing anything?

**Comment by remko** [comment]
@andydude What browser are you using? Have you tried a different browser? Does console tell you something?

**Comment by andydude** [comment]
I'm using Chromium Version 113.0.5672.63 (Official Build) snap (64-bit)
